Algoritmo "estruturas"


Var
contador,contador2,contador3 : inteiro


Inicio
enquanto (contador<=10) faca
   escreval(contador)
   contador <- contador+1
fimenquanto
escreval("________________________")

para contador2 <- 1 ate 10 passo 1 faca
   escreval(contador2)
fimpara
escreval("________________________")

repita
   escreval(contador3)
   contador3<-contador3+1
ate(contador3=11)


Fimalgoritmo