Algoritmo "login2"

Var
usuarioC,senhaC,usuario,senha,login : caractere
procedimento login()
inicio
   enquanto (login = "") faca
   escreval("Digite o usuário:")
   leia(usuario)
   escreval("Digite sua senha:")
   leia(senha)
   limpatela()

   se (senha=senhac)e(usuario=usuarioc)entao
      login<-"correto"
   fimse
fimenquanto
limpatela()
escreval("Login efetuado!")
fimprocedimento

Inicio
usuarioC <- "adm"
senhaC <- "umasenhaincrivel"
login()
Fimalgoritmo