Algoritmo "recepcao"

Var
nome, email : caractere
idade: inteiro
logica : caractere

Inicio
escreval("Boa Tarde! Digite o seu nome:")
leia (nome)
LimpaTela ()
escreval("Digite sua Idade:")
leia (idade)
LimpaTela ()
escreval("Digite seu email: ")
leia (email)
LimpaTela ()
escreval("Cadastro efetuado com sucesso!")
escreval("*******************************")
escreval("Usuário: ",nome)
escreval("Idade: ",idade)
escreval("Email: ",email)
escreval("*******************************")

Fimalgoritmo